spring.application.name=SafeJourney

app.base-url=http://localhost:8080

#DataBase Connections
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/safejourney
spring.datasource.username=root
spring.datasource.password=2580

#JPA/HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#MAIL Settings
# GMAIL SMTP configuration for NON-2FA users


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=safejourney.support@gmail.com
spring.mail.password=poiz kefd dahc gdsz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

